const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer);
        });
    });
}

async function setupEnvironment() {
    console.log('🚀 Welcome to the Employee Management System Setup!');
    console.log('This will help you configure your environment variables.\n');

    const envPath = path.join(__dirname, '..', '.env');

    if (fs.existsSync(envPath)) {
        const overwrite = await askQuestion('⚠️  .env file already exists. Overwrite? (y/N): ');
        if (overwrite.toLowerCase() !== 'y' && overwrite.toLowerCase() !== 'yes') {
            console.log('Setup cancelled.');
            process.exit(0);
        }
    }

    console.log('\n📊 Database Configuration:');
    const mongoUri = await askQuestion('MongoDB URI (default: mongodb://localhost:27017/employee_mgmt): ') || 'mongodb://localhost:27017/employee_mgmt';
    const jwtSecret = await askQuestion('JWT Secret (press enter for random): ') || generateRandomSecret();

    console.log('\n☁️  Cloudinary Configuration (for file uploads):');
    const cloudName = await askQuestion('Cloudinary Cloud Name: ');
    const apiKey = await askQuestion('Cloudinary API Key: ');
    const apiSecret = await askQuestion('Cloudinary API Secret: ');

    console.log('\n🤖 AI Configuration (for chatbot):');
    const togetherApiKey = await askQuestion('Together AI API Key: ');

    console.log('\n📧 Email Configuration (optional):');
    const senderEmail = await askQuestion('Sender Email (optional): ');
    const senderPassword = await askQuestion('Email App Password (optional): ');

    const envContent = `# Generated by Employee Management System Setup
# $(new Date().toISOString())

# Database Configuration
MONGO_URI=${mongoUri}
JWT_SECRET=${jwtSecret}

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME=${cloudName}
CLOUDINARY_API_KEY=${apiKey}
CLOUDINARY_API_SECRET=${apiSecret}

# Together AI Configuration
TOGETHERAI_API_KEY=${togetherApiKey}

# Email Configuration
SENDER_EMAIL=${senderEmail}
SENDER_PASSWORD=${senderPassword}

# API Configuration
NEXT_PUBLIC_API_BASE=http://localhost:5000
NEXT_PUBLIC_CHATBOT_BASE=http://localhost:5001

# Service Configuration
NODE_ENV=development
CHATBOT_HOST=127.0.0.1
CHATBOT_PORT=5001
`;

    fs.writeFileSync(envPath, envContent);

    // Also create backend .env
    const backendEnvPath = path.join(__dirname, '..', 'employee-mgmt-system-main', 'backend', '.env');
    fs.writeFileSync(backendEnvPath, envContent);

    console.log('\n✅ Environment configuration saved to .env');
    console.log('✅ Backend .env file created');
    console.log('\n🎉 Setup complete! You can now run:');
    console.log('   npm run install:all  # Install all dependencies');
    console.log('   npm run dev          # Start in development mode');
    console.log('   npm run docker:up    # Start with Docker\n');

    rl.close();
}

function generateRandomSecret() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
    let result = '';
    for (let i = 0; i < 64; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}

if (require.main === module) {
    setupEnvironment().catch(console.error);
}

module.exports = { setupEnvironment };